#!/usr/local/bin/suid-python --virtualenv=/opt/openerp
"""
Ensures /home/openerp/.ssh/known_hosts is owned by openerp.

Something keeps resetting that file's ownership to root; hopefully this will
both keep other scripts running properly, and provide timing clues to the
identity of the other process.
"""

from __future__ import print_function
from scription import *
from antipathy import Path
from fnx_script_support import Notify
import pwd

@Command(
        test=('pretend error condition and send mail', FLAG)
        )
def check_openerp_known_hosts(test):
    errors = []
    #
    try:
        if test:
            errors.append('testing notifications')
        else:
            openerp_ids = tuple(pwd.getpwnam('openerp')[2:4])
            print('openerp: %r' % (openerp_ids, ))
            kh = Path('/home/openerp/.ssh/known_hosts')
            stat = kh.stat()
            file_ids = stat.st_uid, stat.st_gid
            print('file: %r' % (file_ids, ))
            if openerp_ids != file_ids:
                errors.append('known_hosts is owned by %r' % (file_ids, ))
                print('not owned by openerp')
                # change ownership back to openerp
                kh.chown(*openerp_ids)
    except Exception as e:
        print('oops: %s' % e)
        errors.append(str(e))
    #
    notify = Notify(script_name)
    notify(errors)


Run()

